sonar.projectKey=admin-api
sonar.projectName=Admin API
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/tests/**
